config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #

  get "up" => "rails/health#show", as: :rails_health_check
  # Read all
  get "restaurants", to: "restaurants#index"
  # Create
  get "restaurants/new", to: "restaurants#new"
  post "restaurants", to: "restaurants#create"
  # Read one
  get "restaurants/:id", to: "restaurants#show", as: :restaurant
  # Update
  get "restaurants/:id/edit", to: "restaurants#edit", as: :restaurant_edit
  patch "restaurants/:id", to: "restaurants#update"
  # Delete
  delete "restaurants/:id", to: "restaurants#destroy"
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      #show the form again but with @restaurant in this method
      render 'new', status: :unprocessable_entity
    end
    # No need for app/views/restaurants/create.html.erb

  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path, status: :see_other
  end



  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with model: restaurant do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.label :address %>
  <%= f.text_field :address, class: "form-control" %>
  <%= f.label :rating %>
  <%= f.number_field :rating, class: "form-control" %>
  <%= f.submit "Submit", class: "btn btn-success mt-3" %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit <%= @restaurant.name %></h1>

<!-- app/views/restaurants/edit.html.erb -->
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1 class="mt-2">All Restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant_path(restaurant), class:"text-decoration-none" %></li>
  <% end %>
</ul>

<div class="d-flex">
<%= link_to "Create a new restaurant", restaurants_new_path, class:"text-decoration-none m-2" %>
</div>

app/views/restaurants/new.html.erb
<!-- app/views/restaurants/new.html.erb -->
<div class="m-3">
  <h1>Create a new restaurant</h1>
  <%= render 'form', restaurant: @restaurant %>
</div>

app/views/restaurants/show.html.erb
<div class="m-3">
  <h1>Restaurant <%= @restaurant.name %></h1>

  <p>Location: <%= @restaurant.address %></p>
  <p>Rating: <%= "⭐️" * @restaurant.rating %></p>

  <!-- app/views/restaurants/show.html.erb -->
  <%= link_to "Edit", restaurant_edit_path(@restaurant), class:"text-decoration-none m-2" %>

  <%= link_to "Delete",
    restaurant_path(@restaurant),
    class:"text-decoration-none m-2 btn btn-light",
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %>

  <%= link_to "Back to all restaurants", restaurants_path, class:"text-decoration-none m-2" %>



</div>